<?php

namespace App;

use App\Filters\QueryFilter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Project extends Model
{
    //наименование таблицы в БД
    protected $table = 'projects';

    //разрешенные заполняемые поля модели Project
    protected $fillable = [
        'name', 'budget', 'text', 'is_active', 'code', 'company_id',
    ];

    //связь модели Project один ко многим с моделью Task
    public function tasks()
    {
        return $this->hasMany(Task::class, 'project_id');
    }

    //связь модели Project многие к одному с моделью Company
    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }

    //обработка событий при удалении данных в модели Project
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($project) {
            $project->tasks()->delete();
        });
    }

    //фильтр по модели Project
    public function scopeFilter(Builder $builder, QueryFilter $filter)
    {
        return $filter->apply($builder);
    }
}
