<?php

namespace App;

use App\Filters\QueryFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //наименование таблицы в БД
    protected $table = 'tasks';

    //разрешенные заполняемые поля модели Task
    protected $fillable = [
        'name', 'text', 'time', 'fact_time', 'price', 'limit', 'importance', 'is_active', 'status_id', 'project_id', 'company_id',
    ];

    //связь модели Task многие к одному с моделью TaskStatus
    public function taskStatus()
    {
        return $this->belongsTo(TaskStatus::class, 'status_id');
    }

    //связь модели Task многие к одному с моделью Project
    public function project()
    {
        return $this->belongsTo(Project::class, 'project_id');
    }

    //связь модели Task один ко многим с моделью Comment
    public function comments()
    {
        return $this->hasMany(Comment::class, 'task_id');
    }

    //связь модели Task один ко многим с моделью File
    public function files()
    {
        return $this->hasMany(File::class, 'task_id');
    }

    //связь модели Task многие ко многим с моделью Role
    public function roles()
    {
        return $this->belongsToMany(Role::class, 'roles_tasks', 'task_id', 'role_id')->withPivot('user_id');
    }

    //обработка событий при удалении данных в модели Task
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($task) {
            $task->comments()->delete();
            $task->files()->delete();
            $task->roles()->detach();
        });
    }

    //фильтр по модели Task
    public function scopeFilter(Builder $builder, QueryFilter $filter)
    {
        return $filter->apply($builder);
    }
}
