<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    //наименование таблицы в БД
    protected $table = 'users';

    //разрешенные заполняемые поля модели User
    protected $fillable = [
        'name', 'email', 'phone', 'photo', 'company_id', 'password', 'admin',
    ];

    //скрытые поля модели User
    protected $hidden = [
        'password', 'remember_token',
    ];

    //верификация поля email в модели User
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //связь модели User многие к одному с моделью Company
    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }

    //связь модели User один ко многим с моделью Comments
    public function comments()
    {
        return $this->hasMany(Comment::class, 'user_id');
    }

    //обработка событий при удалении данных в модели User
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($user) {
            $user->comments()->delete();
        });
    }
}
